import { db } from "./db";
import { drinks, type Drink, type InsertDrink } from "@shared/schema";
import { eq } from "drizzle-orm";

export interface IStorage {
  getDrink(id: number): Promise<Drink | undefined>;
  getAllDrinks(): Promise<Drink[]>;
  createDrink(drink: InsertDrink): Promise<Drink>;
  getDrinksByType(type: string): Promise<Drink[]>;
  searchDrinks(query: string): Promise<Drink[]>;
}

export class DatabaseStorage implements IStorage {
  async getDrink(id: number): Promise<Drink | undefined> {
    const [drink] = await db.select().from(drinks).where(eq(drinks.id, id));
    return drink;
  }

  async getAllDrinks(): Promise<Drink[]> {
    return db.select().from(drinks);
  }

  async createDrink(drink: InsertDrink): Promise<Drink> {
    const [newDrink] = await db.insert(drinks).values(drink).returning();
    return newDrink;
  }

  async getDrinksByType(type: string): Promise<Drink[]> {
    return db.select().from(drinks).where(eq(drinks.type, type));
  }

  async searchDrinks(query: string): Promise<Drink[]> {
    const allDrinks = await db.select().from(drinks);
    const lowerQuery = query.toLowerCase();
    return allDrinks.filter(
      (d) =>
        d.name.toLowerCase().includes(lowerQuery) ||
        d.type.toLowerCase().includes(lowerQuery) ||
        d.flavourNotes.toLowerCase().includes(lowerQuery) ||
        d.recommendedFoods.toLowerCase().includes(lowerQuery)
    );
  }
}

export const storage = new DatabaseStorage();

// ============================================
// SEED DATA - British & Irish Drinks Database
// Includes small independent producers and larger businesses
// Price tiers: budget, everyday, premium, luxury
// ============================================
export const seedDrinks: InsertDrink[] = [
  // ============================================
  // TRADITIONAL BRITISH ALES
  // ============================================
  {
    name: "Timothy Taylor's Landlord",
    type: "ale",
    flavourNotes: "Full-bodied with a hoppy, slightly floral aroma and a biscuity malt backbone",
    region: "Yorkshire",
    abv: "4.3%",
    recommendedFoods: "Roast beef, Steak pie, Cheese ploughman's",
    affiliateLink: "https://www.timothytaylor.co.uk",
    description: "A classic Yorkshire pale ale, winner of multiple CAMRA awards. Known for its perfect balance of hop bitterness and malt sweetness.",
    imageUrl: null,
    awards: "CAMRA Champion Beer of Britain (4x winner)",
    reviewLink: "https://untappd.com/b/timothy-taylor-landlord/3815",
    priceTier: "everyday",
  },
  {
    name: "Fuller's London Pride",
    type: "ale",
    flavourNotes: "Marmalade citrus, rich malt with a dry, biscuity finish",
    region: "London",
    abv: "4.7%",
    recommendedFoods: "Fish and chips, Bangers and mash, Sunday roast",
    affiliateLink: "https://www.fullers.co.uk",
    description: "London's iconic amber ale with over 175 years of brewing heritage. A perfectly balanced pint with distinctive marmalade notes.",
    imageUrl: null,
    awards: "CAMRA Champion Best Bitter",
    reviewLink: "https://untappd.com/b/fuller-s-london-pride/5765",
    priceTier: "everyday",
  },
  {
    name: "Black Sheep Best Bitter",
    type: "ale",
    flavourNotes: "Dry and bitter with fruity esters, crisp hoppy character",
    region: "Yorkshire",
    abv: "3.8%",
    recommendedFoods: "Yorkshire pudding, Shepherd's pie, Cheese",
    affiliateLink: "https://www.blacksheepbrewery.co.uk",
    description: "A traditional Yorkshire bitter brewed in Masham using the Yorkshire Square fermentation system.",
    imageUrl: null,
    awards: "SIBA Gold Medal",
    reviewLink: "https://untappd.com/b/black-sheep-brewery-best-bitter/9099",
    priceTier: "budget",
  },
  {
    name: "Adnams Broadside",
    type: "ale",
    flavourNotes: "Rich fruitcake, blackcurrant with a bittersweet malt finish",
    region: "East Anglia",
    abv: "6.3%",
    recommendedFoods: "Game pie, Venison, Christmas pudding",
    affiliateLink: "https://www.adnams.co.uk",
    description: "A dark, rich ruby ale from the Suffolk coast. Named after the 1672 Battle of Sole Bay.",
    imageUrl: null,
    awards: "World Beer Awards Gold",
    reviewLink: "https://untappd.com/b/adnams-broadside/5697",
    priceTier: "everyday",
  },
  // ============================================
  // BREWDOG - CRAFT BEER GIANTS
  // ============================================
  {
    name: "BrewDog Punk IPA",
    type: "ale",
    flavourNotes: "Tropical fruit, pine resin, grapefruit with a crisp bitter finish",
    region: "Scotland",
    abv: "5.4%",
    recommendedFoods: "Burgers, Spicy tacos, Thai curry, BBQ",
    affiliateLink: "https://www.brewdog.com/uk",
    description: "The beer that started a revolution. Scotland's flagship craft IPA - bold, punchy and explosively hoppy.",
    imageUrl: null,
    awards: "World Beer Cup Bronze",
    reviewLink: "https://untappd.com/b/brewdog-punk-ipa/6159",
    priceTier: "everyday",
  },
  {
    name: "BrewDog Hazy Jane",
    type: "ale",
    flavourNotes: "Juicy mango, peach, pineapple with a smooth hazy body",
    region: "Scotland",
    abv: "5.0%",
    recommendedFoods: "Fried chicken, Asian fusion, Fish tacos, Nachos",
    affiliateLink: "https://www.brewdog.com/uk",
    description: "A New England-style hazy IPA bursting with tropical fruit. Smooth, juicy and dangerously drinkable.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/brewdog-hazy-jane/2424982",
    priceTier: "everyday",
  },
  {
    name: "BrewDog Elvis Juice",
    type: "ale",
    flavourNotes: "Zesty grapefruit, orange citrus, piney hops with a tangy finish",
    region: "Scotland",
    abv: "6.5%",
    recommendedFoods: "Grilled seafood, Mexican food, Citrus salads, Spicy wings",
    affiliateLink: "https://www.brewdog.com/uk",
    description: "A grapefruit-infused IPA that's all about big citrus flavour. Bold, zesty and refreshingly different.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/brewdog-elvis-juice/1469130",
    priceTier: "everyday",
  },
  // ============================================
  // MICRO-BREWERIES & CRAFT PRODUCERS
  // ============================================
  {
    name: "Weetwood Cheshire Cat",
    type: "ale",
    flavourNotes: "Smooth malt, subtle hop bitterness, hints of toffee and a clean dry finish",
    region: "Cheshire",
    abv: "4.0%",
    recommendedFoods: "Cheshire cheese, Pork pies, Ploughman's lunch, Roast chicken",
    affiliateLink: "https://www.weetwoodales.co.uk",
    description: "A perfectly balanced blonde ale from Weetwood Ales, a family-run Cheshire micro-brewery. Smooth, refreshing and wonderfully drinkable.",
    imageUrl: null,
    awards: "SIBA Regional Gold",
    reviewLink: "https://untappd.com/b/weetwood-ales-cheshire-cat/22748",
    priceTier: "budget",
  },
  {
    name: "Weetwood Eastgate Ale",
    type: "ale",
    flavourNotes: "Rich caramel malt, dried fruit, gentle spice with a warming finish",
    region: "Cheshire",
    abv: "4.2%",
    recommendedFoods: "Beef stew, Game pie, Mature cheddar, Roast lamb",
    affiliateLink: "https://www.weetwoodales.co.uk",
    description: "A traditional amber ale crafted in the heart of Cheshire. Named after Chester's famous Eastgate Clock.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/weetwood-ales-eastgate-ale/156891",
    priceTier: "budget",
  },
  {
    name: "Thornbridge Jaipur",
    type: "ale",
    flavourNotes: "Tropical citrus burst, passion fruit, grapefruit with a long hoppy finish",
    region: "Derbyshire",
    abv: "5.9%",
    recommendedFoods: "Spicy Thai curry, Jerk chicken, Strong blue cheese, Mexican tacos",
    affiliateLink: "https://www.thornbridgebrewery.co.uk",
    description: "Multi-award winning IPA from Thornbridge. Bold, citrusy and endlessly refreshing - one of Britain's finest craft beers.",
    imageUrl: null,
    awards: "World Beer Awards Champion IPA",
    reviewLink: "https://untappd.com/b/thornbridge-brewery-jaipur/5772",
    priceTier: "premium",
  },
  {
    name: "Hawkshead Windermere Pale",
    type: "ale",
    flavourNotes: "Crisp citrus hop, light biscuit malt, refreshing floral notes",
    region: "Lake District",
    abv: "3.5%",
    recommendedFoods: "Grilled trout, Light salads, Fish pie, Chicken sandwiches",
    affiliateLink: "https://www.hawksheadbrewery.co.uk",
    description: "A sessionable pale ale from the Lake District's award-winning Hawkshead Brewery. Light, zesty and perfect for any occasion.",
    imageUrl: null,
    awards: "SIBA North West Gold",
    reviewLink: "https://untappd.com/b/hawkshead-brewery-windermere-pale/13651",
    priceTier: "everyday",
  },
  {
    name: "Tiny Rebel Cwtch",
    type: "ale",
    flavourNotes: "Caramel sweetness, citrus hops, subtle spice with a smooth mouthfeel",
    region: "Wales",
    abv: "4.6%",
    recommendedFoods: "Welsh rarebit, Lamb dishes, Cheese boards, Hearty stews",
    affiliateLink: "https://www.tinyrebel.co.uk",
    description: "Champion Beer of Britain winner. 'Cwtch' means cuddle in Welsh - a comforting red ale with a hoppy twist.",
    imageUrl: null,
    awards: "CAMRA Champion Beer of Britain",
    reviewLink: "https://untappd.com/b/tiny-rebel-cwtch/356453",
    priceTier: "everyday",
  },
  {
    name: "Siren Craft Brew Soundwave",
    type: "ale",
    flavourNotes: "Pine resin, tropical mango, stone fruit with a balanced bitter finish",
    region: "Berkshire",
    abv: "5.6%",
    recommendedFoods: "Burgers, BBQ ribs, Spicy wings, Strong aged cheeses",
    affiliateLink: "https://www.sirencraftbrew.com",
    description: "A modern West Coast IPA from one of the UK's most innovative breweries. Bold, aromatic and utterly moreish.",
    imageUrl: null,
    awards: "Ratebeer Top 50 UK Brewers",
    reviewLink: "https://untappd.com/b/siren-craft-brew-soundwave/406842",
    priceTier: "premium",
  },
  {
    name: "Burning Sky Plateau",
    type: "ale",
    flavourNotes: "Bright citrus, floral elderflower, soft bitterness with a crisp finish",
    region: "Sussex",
    abv: "3.5%",
    recommendedFoods: "Fresh seafood, Garden salads, Goat's cheese, Light fish dishes",
    affiliateLink: "https://www.burningskybeer.com",
    description: "An elegant session pale from Sussex's acclaimed Burning Sky. Delicate yet flavourful, perfect for contemplative drinking.",
    imageUrl: null,
    awards: "Ratebeer Best UK Brewer",
    reviewLink: "https://untappd.com/b/burning-sky-plateau/744389",
    priceTier: "premium",
  },
  {
    name: "Beavertown Neck Oil",
    type: "ale",
    flavourNotes: "Tropical hop explosion, mango, grapefruit with a smooth sessionable body",
    region: "London",
    abv: "4.3%",
    recommendedFoods: "Street food, Tacos, Fried chicken, Casual pub grub",
    affiliateLink: "https://www.beavertownbrewery.co.uk",
    description: "London's iconic session IPA. Packed with New World hops yet dangerously drinkable.",
    imageUrl: null,
    awards: "World Beer Awards Bronze",
    reviewLink: "https://untappd.com/b/beavertown-brewery-neck-oil/494694",
    priceTier: "everyday",
  },
  {
    name: "Wild Beer Co Bibble",
    type: "ale",
    flavourNotes: "Juicy American hops, ripe peach, subtle sweetness with refreshing bitterness",
    region: "Somerset",
    abv: "4.2%",
    recommendedFoods: "Thai green curry, Grilled prawns, Avocado dishes, Light Asian cuisine",
    affiliateLink: "https://www.wildbeerco.com",
    description: "A bright, juicy pale ale from Wild Beer's Somerset farmhouse brewery. Vibrant hops meet farmhouse soul.",
    imageUrl: null,
    awards: "Great Taste Award",
    reviewLink: "https://untappd.com/b/wild-beer-co-bibble/582393",
    priceTier: "premium",
  },
  // ============================================
  // IRISH STOUTS & BEERS
  // ============================================
  {
    name: "Guinness Draught",
    type: "stout",
    flavourNotes: "Roasted barley, dark chocolate, coffee with a creamy smooth finish",
    region: "Ireland",
    abv: "4.2%",
    recommendedFoods: "Irish stew, Oysters, Beef and Guinness pie, Cheese toasties",
    affiliateLink: "https://www.guinness.com/en-gb",
    description: "The world's most famous stout, brewed at St. James's Gate Dublin since 1759. Iconic, smooth and utterly satisfying.",
    imageUrl: null,
    awards: "World's Best-Selling Stout",
    reviewLink: "https://untappd.com/b/guinness-guinness-draught/3965",
    priceTier: "budget",
  },
  {
    name: "Murphy's Irish Stout",
    type: "stout",
    flavourNotes: "Smooth chocolate, light coffee, subtle caramel with a creamy texture",
    region: "Ireland",
    abv: "4.0%",
    recommendedFoods: "Bangers and mash, Shepherd's pie, Dark chocolate, Cheese",
    affiliateLink: "https://www.murphys.com",
    description: "Cork's beloved stout - smoother and slightly sweeter than its Dublin rival. A true taste of Ireland's second city.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/murphy-s-murphy-s-irish-stout/6046",
    priceTier: "budget",
  },
  {
    name: "Smithwick's Red Ale",
    type: "ale",
    flavourNotes: "Toasted malt, caramel sweetness, subtle hops with a smooth finish",
    region: "Ireland",
    abv: "3.8%",
    recommendedFoods: "Roast pork, Irish soda bread, Cheddar cheese, Meat pies",
    affiliateLink: "https://www.smithwicks.com",
    description: "Ireland's oldest ale, brewed in Kilkenny since 1710. A ruby red ale with a distinctively smooth, malty character.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/smithwick-s-smithwick-s-red-ale/6055",
    priceTier: "budget",
  },
  // ============================================
  // CIDERS
  // ============================================
  {
    name: "Aspall Suffolk Cyder",
    type: "cider",
    flavourNotes: "Crisp apple with honeyed sweetness and a dry, refreshing finish",
    region: "East Anglia",
    abv: "5.5%",
    recommendedFoods: "Pork dishes, Cheese, Light salads",
    affiliateLink: "https://www.aspall.co.uk",
    description: "A premium English cider crafted in Suffolk since 1728. Made from a blend of bittersweet and culinary apples.",
    imageUrl: null,
    awards: "Great Taste Award",
    reviewLink: "https://untappd.com/b/aspall-aspall-suffolk-cyder/11899",
    priceTier: "everyday",
  },
  {
    name: "Westons Vintage Cider",
    type: "cider",
    flavourNotes: "Rich, oaky with toffee apple notes and a smooth, medium-dry finish",
    region: "Herefordshire",
    abv: "8.2%",
    recommendedFoods: "Cheese board, Pork pie, Apple desserts",
    affiliateLink: "https://www.westons-cider.co.uk",
    description: "A premium oak-aged cider from Herefordshire's finest apples. Aged for two years for exceptional depth.",
    imageUrl: null,
    awards: "International Cider Challenge Gold",
    reviewLink: "https://untappd.com/b/westons-cider-vintage/24890",
    priceTier: "premium",
  },
  {
    name: "Thatchers Gold",
    type: "cider",
    flavourNotes: "Golden and smooth with a crisp, refreshing apple taste",
    region: "Somerset",
    abv: "4.8%",
    recommendedFoods: "Ploughman's lunch, Pork chops, Light cheese",
    affiliateLink: "https://www.thatcherscider.co.uk",
    description: "A refreshing medium-dry Somerset cider made from a blend of British apples.",
    imageUrl: null,
    awards: "Great Taste Award 3 Stars",
    reviewLink: "https://untappd.com/b/thatchers-cider-gold/12066",
    priceTier: "budget",
  },
  {
    name: "Magners Original Irish Cider",
    type: "cider",
    flavourNotes: "Crisp apple, light sweetness with a refreshing, easy-drinking character",
    region: "Ireland",
    abv: "4.5%",
    recommendedFoods: "BBQ chicken, Summer salads, Light snacks, Pub food",
    affiliateLink: "https://www.magners.co.uk",
    description: "Ireland's favourite cider, best served over ice. Made with 17 varieties of Irish apples for a perfectly balanced taste.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/magners-magners-original/9608",
    priceTier: "budget",
  },
  // ============================================
  // BRITISH & IRISH GINS
  // ============================================
  {
    name: "Sipsmith London Dry Gin",
    type: "gin",
    flavourNotes: "Juniper-forward with bright citrus, floral notes and a peppery warmth",
    region: "London",
    abv: "41.6%",
    recommendedFoods: "Seafood, Light poultry, Cucumber dishes",
    affiliateLink: "https://www.sipsmith.com",
    description: "Handcrafted in London's first copper pot still for nearly 200 years. A perfectly balanced London Dry Gin.",
    imageUrl: null,
    awards: "IWSC Gold Medal",
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/3853/sipsmith-london-dry-gin",
    priceTier: "premium",
  },
  {
    name: "Cotswolds Dry Gin",
    type: "gin",
    flavourNotes: "Fresh lavender, bay leaf, grapefruit with subtle spice",
    region: "Cotswolds",
    abv: "46%",
    recommendedFoods: "Garden salads, Grilled fish, Mediterranean dishes",
    affiliateLink: "https://www.cotswoldsdistillery.com",
    description: "An aromatic gin distilled with nine carefully considered botanicals from the heart of the Cotswolds.",
    imageUrl: null,
    awards: "San Francisco World Spirits Gold",
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/4973/cotswolds-dry-gin",
    priceTier: "premium",
  },
  {
    name: "Hendrick's Gin",
    type: "gin",
    flavourNotes: "Cucumber, rose petal, citrus with a smooth, rounded finish",
    region: "Scotland",
    abv: "41.4%",
    recommendedFoods: "Cucumber sandwiches, Smoked salmon, Light appetizers",
    affiliateLink: "https://www.hendricksgin.com",
    description: "A distinctively delicious gin made with curious, yet perfectly balanced infusions of cucumber and rose.",
    imageUrl: null,
    awards: "IWSC Gold Outstanding",
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/2491/hendricks-gin",
    priceTier: "premium",
  },
  {
    name: "Beefeater London Dry Gin",
    type: "gin",
    flavourNotes: "Classic juniper, citrus peel, angelica root with a clean finish",
    region: "London",
    abv: "40%",
    recommendedFoods: "Classic G&T snacks, Olives, Nuts, Fish and chips",
    affiliateLink: "https://www.beefeatergin.com",
    description: "London's original gin, distilled in the heart of the city since 1863. A true classic that never goes out of style.",
    imageUrl: null,
    awards: "IWSC Gold",
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/478/beefeater-london-dry-gin",
    priceTier: "everyday",
  },
  {
    name: "Dingle Original Gin",
    type: "gin",
    flavourNotes: "Rowan berry, fuchsia, bog myrtle with coastal botanicals",
    region: "Ireland",
    abv: "42.5%",
    recommendedFoods: "Oysters, Fresh crab, Smoked fish, Light seafood",
    affiliateLink: "https://www.dingledistillery.ie",
    description: "A unique Irish gin featuring wild botanicals foraged from the Dingle Peninsula. Ireland's craft distilling at its finest.",
    imageUrl: null,
    awards: "World Gin Awards Gold",
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/4967/dingle-original-gin",
    priceTier: "premium",
  },
  // ============================================
  // WHISKIES - SCOTCH & IRISH
  // ============================================
  {
    name: "Glenfiddich 12 Year Old",
    type: "whisky",
    flavourNotes: "Fresh pear, subtle oak, butterscotch with a long smooth finish",
    region: "Speyside",
    abv: "40%",
    recommendedFoods: "Smoked salmon, Dark chocolate, Aged cheese",
    affiliateLink: "https://www.glenfiddich.com",
    description: "The world's most awarded single malt Scotch whisky. Matured in American and European oak casks.",
    imageUrl: null,
    awards: "World's Most Awarded Single Malt",
    reviewLink: "https://www.whiskybase.com/whiskies/whisky/1164/glenfiddich-12-year-old",
    priceTier: "premium",
  },
  {
    name: "Laphroaig 10 Year Old",
    type: "whisky",
    flavourNotes: "Intensely peaty, smoky seaweed with hints of iodine and a long sweet finish",
    region: "Islay",
    abv: "40%",
    recommendedFoods: "Oysters, Blue cheese, Smoked meats",
    affiliateLink: "https://www.laphroaig.com",
    description: "A bold, smoky Islay single malt. The most richly flavoured of all Scotch whiskies.",
    imageUrl: null,
    awards: "World Whiskies Awards Gold",
    reviewLink: "https://www.whiskybase.com/whiskies/whisky/2893/laphroaig-10-year-old",
    priceTier: "premium",
  },
  {
    name: "Jameson Irish Whiskey",
    type: "whisky",
    flavourNotes: "Smooth vanilla, toasted wood, subtle spice with a mellow finish",
    region: "Ireland",
    abv: "40%",
    recommendedFoods: "Irish soda bread, Apple pie, Cheese board, Dark chocolate",
    affiliateLink: "https://www.jamesonwhiskey.com/en-GB",
    description: "Ireland's favourite whiskey, triple-distilled for exceptional smoothness. Perfect neat, on ice, or in an Irish coffee.",
    imageUrl: null,
    awards: "World's Best-Selling Irish Whiskey",
    reviewLink: "https://www.whiskybase.com/whiskies/whisky/45645/jameson",
    priceTier: "everyday",
  },
  {
    name: "Bushmills Original",
    type: "whisky",
    flavourNotes: "Light honey, vanilla, fresh fruit with a smooth, easy finish",
    region: "Ireland",
    abv: "40%",
    recommendedFoods: "Light desserts, Vanilla ice cream, Shortbread, Mild cheese",
    affiliateLink: "https://www.bushmills.com",
    description: "From the world's oldest licensed distillery (1608), a smooth and approachable Irish whiskey with a light, fruity character.",
    imageUrl: null,
    awards: "San Francisco World Spirits Silver",
    reviewLink: "https://www.whiskybase.com/whiskies/whisky/3007/bushmills-original",
    priceTier: "everyday",
  },
  {
    name: "Johnnie Walker Black Label",
    type: "whisky",
    flavourNotes: "Rich dried fruit, sweet vanilla, smoky finish with warming spice",
    region: "Scotland",
    abv: "40%",
    recommendedFoods: "Grilled steak, Dark chocolate, Aged cheddar, Christmas cake",
    affiliateLink: "https://www.johnniewalker.com",
    description: "A masterful blend of whiskies aged at least 12 years. Deep, complex and exceptionally smooth.",
    imageUrl: null,
    awards: "IWSC Gold Outstanding",
    reviewLink: "https://www.whiskybase.com/whiskies/whisky/63726/johnnie-walker-black-label",
    priceTier: "premium",
  },
  // ============================================
  // RUM
  // ============================================
  {
    name: "Pusser's British Navy Rum",
    type: "rum",
    flavourNotes: "Rich molasses, butterscotch, vanilla with warming spice notes",
    region: "London",
    abv: "54.5%",
    recommendedFoods: "Jerk chicken, Spicy curries, Chocolate desserts",
    affiliateLink: "https://www.pussersrum.com",
    description: "The original British Royal Navy rum, blended to the Admiralty's specifications since 1655.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://www.diffordsguide.com/beer-wines-spirits/2915/pussers-blue-label-navy-rum",
    priceTier: "premium",
  },
  // ============================================
  // ENGLISH WINES
  // ============================================
  {
    name: "Nyetimber Classic Cuvée",
    type: "wine",
    flavourNotes: "Toasted brioche, honey, citrus blossom with fine bubbles",
    region: "Sussex",
    abv: "12%",
    recommendedFoods: "Oysters, Canapés, Celebration dishes",
    affiliateLink: "https://www.nyetimber.com",
    description: "England's finest sparkling wine, rivalling the best Champagnes. Grown on the chalk downs of Sussex.",
    imageUrl: null,
    awards: "Decanter World Wine Awards Gold",
    reviewLink: "https://www.vivino.com/nyetimber-classic-cuvee/w/22925",
    priceTier: "luxury",
  },
  {
    name: "Chapel Down Bacchus",
    type: "wine",
    flavourNotes: "Elderflower, gooseberry, crisp green apple with mineral notes",
    region: "Kent",
    abv: "12.5%",
    recommendedFoods: "Fresh seafood, Asparagus, Goat's cheese",
    affiliateLink: "https://www.chapeldown.com",
    description: "England's signature white grape, producing wines with distinctive aromatic character.",
    imageUrl: null,
    awards: "IWC Silver Medal",
    reviewLink: "https://www.vivino.com/chapel-down-bacchus/w/30858",
    priceTier: "premium",
  },
  // ============================================
  // NON-ALCOHOLIC BRITISH & IRISH DRINKS
  // Always highlighted as alcohol-free options
  // ============================================
  {
    name: "Yorkshire Tea",
    type: "tea",
    flavourNotes: "Rich, malty with a robust character and a smooth, comforting finish",
    region: "Yorkshire",
    abv: "0%",
    recommendedFoods: "Scones with cream, Full English breakfast, Biscuits, Sunday roast",
    affiliateLink: "https://www.yorkshiretea.co.uk",
    description: "Britain's favourite tea brand, known for its proper brew strength and comforting character. A cup of Yorkshire is never just a cup of tea.",
    imageUrl: null,
    awards: "Great Taste Award 3 Stars",
    reviewLink: null,
    priceTier: "budget",
  },
  {
    name: "Twinings English Breakfast",
    type: "tea",
    flavourNotes: "Bold, full-bodied with bright notes and a satisfying depth",
    region: "London",
    abv: "0%",
    recommendedFoods: "Full English breakfast, Toast with marmalade, Pastries, Eggs",
    affiliateLink: "https://www.twinings.co.uk",
    description: "A classic British blend since 1706 from the world's oldest tea company. The perfect accompaniment to a hearty British breakfast.",
    imageUrl: null,
    awards: "Royal Warrant Holder",
    reviewLink: null,
    priceTier: "budget",
  },
  {
    name: "Fentimans Ginger Beer",
    type: "soft drink",
    flavourNotes: "Fiery ginger with botanical complexity, warming spice and a refreshing finish",
    region: "Northumberland",
    abv: "0%",
    recommendedFoods: "Spicy curries, Asian cuisine, Grilled meats, Cheese",
    affiliateLink: "https://www.fentimans.com",
    description: "Botanically brewed using a time-honoured recipe since 1905. Made with real ginger root for authentic heat and flavour.",
    imageUrl: null,
    awards: "Great Taste Award Gold",
    reviewLink: null,
    priceTier: "everyday",
  },
  {
    name: "Belvoir Elderflower Pressé",
    type: "soft drink",
    flavourNotes: "Delicate elderflower, light honey sweetness with subtle citrus notes",
    region: "Leicestershire",
    abv: "0%",
    recommendedFoods: "Light salads, Fish dishes, Afternoon tea, Summer picnics",
    affiliateLink: "https://www.belvoirfarm.co.uk",
    description: "Handcrafted on a Leicestershire farm using freshly picked elderflowers. A quintessentially English refreshment.",
    imageUrl: null,
    awards: "Great Taste Award 3 Stars",
    reviewLink: null,
    priceTier: "everyday",
  },
  {
    name: "Fever-Tree Tonic Water",
    type: "soft drink",
    flavourNotes: "Crisp quinine bitterness, subtle citrus with pure spring water freshness",
    region: "London",
    abv: "0%",
    recommendedFoods: "Seafood, Light appetizers, Mediterranean dishes, Cheese platters",
    affiliateLink: "https://www.fever-tree.com",
    description: "Premium tonic water made with the finest quinine from the Congo and natural botanicals. If 3/4 of your drink is the mixer, make it the best.",
    imageUrl: null,
    awards: "Queen's Award for Enterprise",
    reviewLink: null,
    priceTier: "everyday",
  },
  {
    name: "Fentimans Curiosity Cola",
    type: "soft drink",
    flavourNotes: "Warming ginger, cinnamon spice with botanical depth and natural sweetness",
    region: "Northumberland",
    abv: "0%",
    recommendedFoods: "Burgers, Pizza, BBQ dishes, Pub food classics",
    affiliateLink: "https://www.fentimans.com",
    description: "A botanically brewed cola made with natural plant extracts. Complex, grown-up and utterly delicious.",
    imageUrl: null,
    awards: "Great Taste Award",
    reviewLink: null,
    priceTier: "everyday",
  },
  {
    name: "Luscombe Sicilian Lemonade",
    type: "soft drink",
    flavourNotes: "Zesty lemon, light sweetness with a clean, refreshing finish",
    region: "Devon",
    abv: "0%",
    recommendedFoods: "Fish and chips, Grilled chicken, Summer salads, Light lunches",
    affiliateLink: "https://www.luscombe.co.uk",
    description: "Organic lemonade made with Sicilian lemons and pure Dartmoor spring water. Simple, honest refreshment from Devon.",
    imageUrl: null,
    awards: "Soil Association Organic Certified",
    reviewLink: null,
    priceTier: "everyday",
  },
  {
    name: "Britvic J2O Orange & Passion Fruit",
    type: "soft drink",
    flavourNotes: "Tropical passion fruit, sweet orange with a refreshing, fruity finish",
    region: "Hertfordshire",
    abv: "0%",
    recommendedFoods: "Pub snacks, Light meals, Party food, Chicken dishes",
    affiliateLink: "https://www.britvic.com",
    description: "Britain's favourite premium fruit juice drink. Perfect for those who want something special without alcohol.",
    imageUrl: null,
    awards: null,
    reviewLink: null,
    priceTier: "budget",
  },
  {
    name: "BrewDog Punk AF",
    type: "ale",
    flavourNotes: "Tropical hops, citrus, pine with the same punch as Punk IPA - zero alcohol",
    region: "Scotland",
    abv: "0%",
    recommendedFoods: "Burgers, Spicy food, BBQ, Pub classics",
    affiliateLink: "https://www.brewdog.com/uk",
    description: "All the flavour and attitude of Punk IPA, with absolutely no alcohol. Proof that alcohol-free doesn't mean flavour-free.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/brewdog-punk-af/2963619",
    priceTier: "everyday",
  },
  {
    name: "Guinness 0.0",
    type: "stout",
    flavourNotes: "Roasted barley, coffee, dark chocolate with a creamy head - zero alcohol",
    region: "Ireland",
    abv: "0%",
    recommendedFoods: "Irish stew, Oysters, Beef pie, Cheese toasties",
    affiliateLink: "https://www.guinness.com/en-gb",
    description: "The iconic taste of Guinness with 0.0% alcohol. Same beautiful stout, same smooth taste, no alcohol.",
    imageUrl: null,
    awards: null,
    reviewLink: "https://untappd.com/b/guinness-guinness-0-0/4267689",
    priceTier: "everyday",
  },
  {
    name: "Barry's Tea Gold Blend",
    type: "tea",
    flavourNotes: "Strong, full-bodied with a rich golden colour and satisfying depth",
    region: "Ireland",
    abv: "0%",
    recommendedFoods: "Irish breakfast, Soda bread, Scones, Afternoon treats",
    affiliateLink: "https://www.barrystea.ie",
    description: "Ireland's favourite tea, beloved for its strong, distinctive flavour. The taste of home for generations of Irish families.",
    imageUrl: null,
    awards: "Great Taste Award",
    reviewLink: null,
    priceTier: "budget",
  },
];

export async function seedDatabase(): Promise<void> {
  const existingDrinks = await db.select().from(drinks);
  if (existingDrinks.length === 0) {
    console.log("Seeding drinks database...");
    for (const drink of seedDrinks) {
      await db.insert(drinks).values(drink);
    }
    console.log(`Seeded ${seedDrinks.length} British & Irish drinks`);
  } else {
    console.log(`Database already has ${existingDrinks.length} drinks`);
  }
}
